version: '3'
services:
  # mysql:
  #   hostname: mysql
  #   image: mysql:latest    
  #   container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
  #   restart: always # 设置容器自启模式
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
  #   environment:
  #     - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
  #     - MYSQL_ROOT_PASSWORD=123456 # 设置root密码
  #   ports:
  #       - "3306:3306"
  #   privileged: true
  
  rtmp-hls:
    hostname: rtmp-hls
    image: alqutami/rtmp-hls:latest
    container_name: rtmp-hls
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
    privileged: true
  redis:  
    hostname: redis
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server /etc/redis.conf # 启动redis命令
    environment:
      - TZ=Asia/Shanghai
    volumes:
       - ./redis.conf:/etc/redis.conf
    ports:
        - "6379:6379"
    privileged: true
   
  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    ports: 
      - "9092:9092"
    container_name: kafka
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.9:9092
      KAFKA_BROKER_ID: 1
    privileged: true
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  es-master:
    image:  elasticsearch
    container_name: es-master
    restart: always
    ports:
     - "9200:9200"
     - "9300:9300"
    privileged: true